name: OpenGX and FreeGLUT
on:
  push:
    branches:
    - master
jobs:
  build-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
  #  - name: Install OpenGX
  #    run: |
  #      cd .
  #      git clone https://github.com/devkitPro/opengx.git
  #      cd opengx
  #      mkdir build && cd build
  #      cmake -DCMAKE_TOOLCHAIN_FILE="$DEVKITPRO/cmake/Wii.cmake" ..
  #     make && sudo make install
    - name: Install FreeGLUT
      run: |
        cd .
        git clone https://github.com/freeglut/freeglut.git
        cd freeglut
        mkdir build && cd build
        cmake -DCMAKE_TOOLCHAIN_FILE="$DEVKITPRO/cmake/Wii.cmake" -DFREEGLUT_BUILD_DEMOS=OFF ..
        make && sudo make install
    - name: Compile
      run: |
        cd .
        make -f Makefile.wiiopengx -j$(nproc)
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: freeglut
        path: |
          ./*.dol
