name: OpenGX SDL2 FreeGLUT
on:
  push:
    branches:
    - with-tutorials
jobs:
  build-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        cd .
        make -f Makefile.wiiopengx -j$(nproc)
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: |
          ./*.dol
